dotenv: .env
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
networks:
  ropsten:
    verify: True
  mainnet-fork:
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
