dotenv: .env
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0'
networks:
  ropsten:
    verify: True
  rinkeby:
    verify: True
    openseaProxyRegistry: '0xf57b2c51ded3a29e6891aba85459d600256cf317'
  mainnet:
    verify: True
    openseaProxyRegistry: '0xa5409ec958c83c3f309868babaca7c86dcb077c1'
  mainnet-fork:
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
